name: Node.js CI

on:
  push:
    branches: master
  pull_request:

jobs:
  nodejs:
    uses: zakodium/workflows/.github/workflows/nodejs.yml@nodejs-v1
    with:
      node-version-matrix: '[14, 16]'
      lint-check-types: true
